#ifndef __notus_ownderdraw_paint_strategies_ids__hpp
#define __notus_ownderdraw_paint_strategies_ids__hpp

#define RED_FOCUSED_COLOR 255
#define GREEN_FOCUSED_COLOR 155
#define BLUE_FOCUSED_COLOR 0

#define CHECK_BOX_PAINT_ID "1"
#define CHECK_BOX_CHECKED_PAINT_ID "2"

#define PUSH_BUTTON_UP_PAINT_ID "3"
#define PUSH_BUTTON_DOWN_PAINT_ID "4"
#define PUSH_BUTTON_DESIBLE_PAINT_ID "5"

#define RADIO_BUTTON_PAINT_ID "6"
#define RADIO_BUTTON_SELECTED_PAINT_ID "7"

#define TAB_BOTTOM_BUTTON_PAINT_ID "8"
#define TAB_BOTTOM_BUTTON_SELECTED_PAINT_ID "9"

#define TOGGLE_BUTTON_UP_PAINT_ID "10"
#define TOGGLE_BUTTON_DOWN_PAINT_ID "11"
#define TOGGLE_BUTTON_DESIBLE_PAINT_ID "12"

#define SCROLL_UP_BUTTON_UP_PAINT_ID "13"
#define SCROLL_UP_BUTTON_DOWN_PAINT_ID "14"

#define SCROLL_DOWN_BUTTON_UP_PAINT_ID "15"
#define SCROLL_DOWN_BUTTON_DOWN_PAINT_ID "16"

#define DROPDOWN_BUTTON_UP_PAINT_ID "17"
#define DROPDOWN_BUTTON_DOWN_PAINT_ID "18"
#define DROPDOWN_BUTTON_DESIBLE_PAINT_ID "19"

#define GLYHP_BUTTON_UP_PAINT_ID "20"
#define GLYHP_BUTTON_DOWN_PAINT_ID "21"
#define GLYHP_BUTTON_DESIBLE_PAINT_ID "22"

#define SCROLL_THUMB_BUTTON_UP_PAINT_ID "23"
#define SCROLL_THUMB_BUTTON_DOWN_PAINT_ID "24"

#define SCROLL_BOX_PAINT_ID "25"

#define HINT_BOX_PAINT_ID "26"

#endif