#pragma once

#define MAIN_WINDOW_FRAME_RES_ID 1
#define MAIN_WINDOW_FRAME_MENU_BUTTON_RES_ID 1
#define MAIN_WINDOW_FRAME_GAME_BUTTON_RES_ID 2
#define MAIN_WINDOW_FRAME_OPTIONS_BUTTON_RES_ID 3

// new FORM start
#define MENU_FORM_RES_ID 2
#define MENU_FORM_USER_LABEL_RES_ID 1
#define MENU_FORM_USER_BUTTON_RES_ID 2
#define MENU_FORM_SELECTPUZZLEBUTTON_RES_ID 3
#define MENU_FORM_BUILDPUZZLEBUTTON_RES_ID 4
#define MENU_FORM_HELPBUTTON_RES_ID 5
#define MENU_FORM_ABOUTBUTTON_RES_ID 6
#define MENU_FORM_REGISTERBUTTON_RES_ID 7
#define MENU_FORM_EXITBUTTON_RES_ID 8
#define MENU_FORM_OPEN_FILE_RES_ID 9
#define MENU_FORM_SAVE_AS_RES_ID 10
#define MENU_FORM_CANCEL 11

// new FORM start
#define OPTIONS_FORM_RES_ID 3

#define OPTIONS_FORM_GAME_BUTTON_RES_ID 1
#define OPTIONS_FORM_ASSISTANCE_BUTTON_RES_ID 2
#define OPTIONS_FORM_STATISTICS_BUTTON_RES_ID 3
#define OPTIONS_FORM_GRID_IMPUT_BUTTON_RES_ID 4
#define OPTIONS_FORM_PREFERENCES_BUTTON_RES_ID 5
#define OPTIONS_FORM_tabFrame_RES_ID 6
#define OPTIONS_FORM_HELP_BUTTON_RES_ID 7

// new  sub FORM start
#define OPTIONS_GAME_FORM_RES_ID 4

#define OPTIONS_GAME_Marks_Lable_RES_ID 15
#define OPTIONS_GAME_FillValidMarks_BUTTON_RES_ID 16
#define OPTIONS_GAME_FillAllMarks_BUTTON_RES_ID 17
#define OPTIONS_GAME_ClearMarks_BUTTON_RES_ID 18
#define OPTIONS_GAME_Wrong_LABLE_RES_ID 19
#define OPTIONS_GAME_RemoveWrong_BUTTON_RES_ID 20
#define OPTIONS_GAME_ReplaceWrong_BUTTON_RES_ID 21
#define OPTIONS_GAME_Puzzle_LABLE_RES_ID 22
#define OPTIONS_GAME_CheckPuzzle_BUTTON_RES_ID 23
#define OPTIONS_GAME_ResetPuzzle_BUTTON_RES_ID 24
#define OPTIONS_GAME_SolvePuzzle_BUTTON_RES_ID 25
#define OPTIONS_GAME_GameInfo_BUTTON_RES_ID 26

// new  sub FORM start
#define OPTIONS_ASSISTANCE_FORM_RES_ID 5

#define OPTIONS_ASSISTANCE_AutoPencilMarks_BUTTON_RES_ID 37
#define OPTIONS_ASSISTANCE_AllowOnlyValidEntries_BUTTON_RES_ID 38
#define OPTIONS_ASSISTANCE_FlagMistakes_BUTTON_RES_ID 39
#define OPTIONS_ASSISTANCE_ShowGuideLines_BUTTON_RES_ID 41 

#define OPTIONS_ASSISTANCE_Disabled_BUTTON_RES_ID 52
#define OPTIONS_ASSISTANCE_MarkIllegalSquares_BUTTON_RES_ID 53
#define OPTIONS_ASSISTANCE_MarkLegalSquares_BUTTON_RES_ID 54
#define OPTIONS_ASSISTANCE_SquaresContainingTheDigit_BUTTON_RES_ID 55
#define OPTIONS_ASSISTANCE_IllegalLegalAndContainin_BUTTON_RES_ID 56
#define OPTIONS_ASSISTANCE_OnTabClueDigits_GROUP_RES_ID 57

// new  sub FORM start
#define OPTIONS_PREFERENCES_FORM_RES_ID 6

#define OPTIONS_PREFERENCES_Sound_BUTTON_RES_ID 67
#define OPTIONS_PREFERENCES_Digits_BUTTON_RES_ID 68
#define OPTIONS_PREFERENCES_Letters_BUTTON_RES_ID 69
#define OPTIONS_PREFERENCES_gridSymbols_GROUP_RES_ID 70

#define OPTIONS_PREFERENCES_Clear_BUTON_RES_ID 81
#define OPTIONS_PREFERENCES_Chess_BUTON_RES_ID 82
#define OPTIONS_PREFERENCES_GridPaintType_GROUP_RES_ID 83

#define OPTIONS_PREFERENCES_EnteringNumbers_COMBO_RES_ID 95
#define	OPTIONS_PREFERENCES_languages_COMBO_RES_ID 96
#define OPTIONS_PREFERENCES_EnteringNumbers_LABEL_RES_ID 97
 
// new  sub FORM start
#define OPTIONS_STATISTICS_FORM_RES_ID 8

#define OPTIONS_STATISTICS_Filter_LABEL_RES_ID 102
#define OPTIONS_STATISTICS_gameLevel_COMBO_RES_ID 103
#define OPTIONS_STATISTICS_gridSize_COMBO_RES_ID 104
#define OPTIONS_STATISTICS_DataList_BUTON_RES_ID 105

// new FORM start
#define SELECT_PUZZLE_FORM_RES_ID 9

#define SELECT_PUZZLE_ok_BUTTON_RES_ID 1
#define SELECT_PUZZLE_puzzlesName_BUTTON_RES_ID 3
#define SELECT_PUZZLE_selectPuzzle_LABEL_RES_ID 4

#define SELECT_PUZZLE_gridSize_COMBO_RES_ID 5
#define SELECT_PUZZLE_gameLevel_COMBO_RES_ID 6


// new FORM start
#define BUILD_PUZZLE_FORM_RES_ID 10

#define BUILD_PUZZLE_build_BUTTON_RES_ID 1

#define BUILD_PUZZLE_gameLevel_COMBO_RES_ID 2
#define BUILD_PUZZLE_gridSize_COMBO_RES_ID 3

#define BUILD_PUZZLE_list_RES_ID 4

#define BUILD_PUZZLE_label_RES_ID 5
#define BUILD_PUZZLE_used_techniques_LABEL_RES_ID 6
#define BUILD_PUZZLE_FORM_CANCEL_BUTTON_ID 7

// new FORM start
#define USERS_FORM_RES_ID 11

#define USERS_new_BUTTON_RES_ID 1
#define USERS_edit_BUTTON_RES_ID 2
#define USERS_delete_BUTTON_RES_ID 3
#define USERS_ok_BUTTON_RES_ID 4

#define USERS_users_LIST_RES_ID 5
#define USERS_name_LABEL_RES_ID 6
 

// new FORM start
#define REGISTRATION_FORM_RES_ID 12

#define REGISTRATION_EnterKey_BUTTON_RES_ID 1
#define REGISTRATION_TryDemo_BUTTON_RES_ID 2

#define REGISTRATION_howToUnlock_LIST_RES_ID 3

#define REGISTRATION_registration_LABEL_RES_ID 4
#define REGISTRATION_hotsyncname_LABEL_RES_ID 5



// new FORM start
#define HELP_FORM_RES_ID 13

#define HELP_help_LABEL_RES_ID 1
#define HELP_textbox_RES_ID 2


// new FORM start
#define ABOUT_FORM_RES_ID 14

#define ABOUT_lable_LABEL_RES_ID 1
#define ABOUT_textbox_RES_ID 2


// new FORM start
#define OK_CANCEL_FORM_RES_ID 15
#define OK_CANCEL_text_LABEL_RES_ID 1
#define OK_CANCEL_ok_BUTTON_RES_ID 2
#define OK_CANCEL_cancel_BUTTON_RES_ID 3
#define	OK_CANCEL_label_LABLE_RES_ID 4



// new FORM Game
#define GAME_FORM_RES_ID 16

#define GAME_FORM_TOOLTIP_BUTTON_RES_ID 5

#define GAME_FORM_GRID_RES_ID 6
#define GAME_FORM_GRID_IN_FIXED_TOPOLOGY_RES_ID 7
#define GAME_FORM_GRID_IN_PRESENTATION_MOD_RES_ID 8
#define GAME_FORM_CLOCK_RES_ID 10
#define GAME_FORM_HINT_HELP_DIALOG_BUTTON_RES_ID 11

#define GAME_FORM_SETTINGS_BUTTON_RES_ID 12 
#define GAME_FORM_HOME_BUTTON_RES_ID 13
#define GAME_FORM_SETTINGS2_BUTTON_RES_ID 14 



// new FORM sudoku
#define PUZZLE_INFO_FORM_RES_ID 18

#define PUZZLE_INFO_FORM_info_LIST_RES_ID 1
#define PUZZLE_INFO_FORM_ok_BUTTON_RES_ID 2
#define PUZZLE_INFO_FORM_group_GROUP_RES_ID 3


// new FORM sudoku
#define PROGRES_FORM_RES_ID 19

#define PROGRES_FORM_ok_BUTTON_RES_ID 1
#define PROGRES_FORM_group_GROUP_RES_ID 2
#define PROGRES_FORM_check_puzzles_LABLE_RES_ID 3
#define PROGRES_FORM_counter_LABLE_RES_ID 4



// new FORM start
#define EDITBOX_FORM_RES_ID 20

#define EDITBOX_bg_LABEL_RES_ID 1
#define EDITBOX_ok_BUTTON_RES_ID 2
#define EDITBOX_cancel_BUTTON_RES_ID 3
#define EDITBOX_editbox_BUTTON_RES_ID 4


// new FORM start
#define INVALID_REFISTRATION_CODE_FORM 21

#define INVALID_REFISTRATION_CODE_bg_LABEL_RES_ID 1
#define INVALID_REFISTRATION_CODE_label_LABEL_RES_ID 2
#define INVALID_REFISTRATION_CODE_textbox1_RES_ID 3
#define INVALID_REFISTRATION_CODE_ok_BUTTON_ID 5

// new FORM start
#define HELP_DIALOG_FORM_RES_ID 22

#define HELP_DIALOG_ok_BUTTON_RES_ID 1
#define HELP_DIALOG_textbox_RES_ID 2
#define HELP_DIALOG_groupbox_RES_ID 3

// new FORM start
#define CHANGE_LANGUAGE_DIALOG_FORM 23

#define CHANGE_LANGUAGE_DIALOG_bg_LABEL_RES_ID 1
#define CHANGE_LANGUAGE_DIALOG_label_LABEL_RES_ID 2
#define CHANGE_LANGUAGE_DIALOG_ok_BUTTON_ID 3
#define CHANGE_LANGUAGE_DIALOG_cancel_BUTTON_ID 4

// new FORM start
#define CHANGE_LANGUAGE_DIALOG_languages_COMBO_RES_ID 5

#define WAIT_FORM 24
#define WAIT_FORM_title_LABEL_RES_ID 1
#define WAIT_FORM_lessage_LABEL_RES_ID 2

// new FORM start
#define OK_FORM_RES_ID 25
#define OK_boxlabel_LABEL_RES_ID 1
#define OK_ok_BUTTON_RES_ID 2
#define	OK_label_LABLE_RES_ID 3


// new FORM start
#define FAKE_EDITBOX_FORM_RES_ID 26

#define FAKE_EDITBOX_bg_LABEL_RES_ID 1
#define FAKE_EDITBOX_ok_BUTTON_RES_ID 2
#define FAKE_EDITBOX_cancel_BUTTON_RES_ID 3
#define FAKE_EDITBOX_editbox_BUTTON_RES_ID 4
#define FAKE_EDITBOX_keypad_box_BUTTON_RES_ID 5

