#pragma once



#define PATTERN_TYPES_RANGE_START 100

#define ILLEGAL_VALUE (PATTERN_TYPES_RANGE_START + 0)
#define ILLEGAL_CANDIDATE (PATTERN_TYPES_RANGE_START + 1)
#define NAKED_SINGLE (PATTERN_TYPES_RANGE_START + 2)
#define HIDDEN_SINGLE (PATTERN_TYPES_RANGE_START + 3)
#define BOX_LINE_REDUCTION (PATTERN_TYPES_RANGE_START + 4)
#define POINTING_PAIR (PATTERN_TYPES_RANGE_START + 5)
#define HIDDEN_PAIR (PATTERN_TYPES_RANGE_START + 6)
#define HIDDEN_TRIPLE (PATTERN_TYPES_RANGE_START + 7)
#define HIDDEN_QUAD (PATTERN_TYPES_RANGE_START + 8)
#define NAKED_PAIR (PATTERN_TYPES_RANGE_START + 9)
#define NAKED_TRIPLE (PATTERN_TYPES_RANGE_START + 10)
#define NAKED_QUAD (PATTERN_TYPES_RANGE_START + 11)
#define REMOTE_PAIR (PATTERN_TYPES_RANGE_START + 12)
#define X_WING (PATTERN_TYPES_RANGE_START + 13)
#define SWORD_FISH (PATTERN_TYPES_RANGE_START + 14)
#define JELLY_FISH (PATTERN_TYPES_RANGE_START + 15)
#define PATTERN_TYPES_RANGE_END (JELLY_FISH + 1)




#define NO_PATTERN_FOUND 190

#define GAME_LEVEL_EMPTY 200
#define GAME_LEVEL_BEGINNER 201
#define GAME_LEVEL_INTERMEDIATE 202
#define GAME_LEVEL_ADVANCED 203
#define GAME_LEVEL_MASTER 204
#define GAME_LEVEL_SORCERER 205
#define GAME_LEVEL_CUSTOM 206


#define STATISTICS_SOLVED_PUZZLES 210
#define STATISTICS_MIN_TIME 211
#define STATISTICS_MAX_TIME 212
#define STATISTICS_AVERAGE_TIME 213

#define GAME_GRID_SOLVED 220
#define SUCCESSFUL_REGISTRATION  221

#define OPTIONS_PREFERENCES_FixedButtons1_ID 230
#define OPTIONS_PREFERENCES_FixedButtons2_ID 231
#define OPTIONS_PREFERENCES_NumericKeyboard1_ID 232
#define OPTIONS_PREFERENCES_NumericKeyboard2_ID 233
#define OPTIONS_PREFERENCES_ButtonsInAColumn_ID 234
#define OPTIONS_PREFERENCES_ButtonsInARow_ID 235


#define PATTERN_HELP_TYPES_RANGE_START 250

#define ILLEGAL_VALUE_HELP (PATTERN_HELP_TYPES_RANGE_START + 0)
#define ILLEGAL_CANDIDATE_HELP (PATTERN_HELP_TYPES_RANGE_START + 1)
#define NAKED_SINGLE_HELP (PATTERN_HELP_TYPES_RANGE_START + 2)
#define HIDDEN_SINGLE_HELP (PATTERN_HELP_TYPES_RANGE_START + 3)
#define BOX_LINE_REDUCTION_HELP (PATTERN_HELP_TYPES_RANGE_START + 4)
#define POINTING_PAIR_HELP (PATTERN_HELP_TYPES_RANGE_START + 5)
#define HIDDEN_PAIR_HELP (PATTERN_HELP_TYPES_RANGE_START + 6)
#define HIDDEN_TRIPLE_HELP (PATTERN_HELP_TYPES_RANGE_START + 7)
#define HIDDEN_QUAD_HELP (PATTERN_HELP_TYPES_RANGE_START + 8)
#define NAKED_PAIR_HELP (PATTERN_HELP_TYPES_RANGE_START + 9)
#define NAKED_TRIPLE_HELP (PATTERN_HELP_TYPES_RANGE_START + 10)
#define NAKED_QUAD_HELP (PATTERN_HELP_TYPES_RANGE_START + 11)
#define REMOTE_PAIR_HELP (PATTERN_HELP_TYPES_RANGE_START + 12)
#define X_WING_HELP (PATTERN_HELP_TYPES_RANGE_START + 13)
#define SWORD_FISH_HELP (PATTERN_HELP_TYPES_RANGE_START + 14)
#define JELLY_FISH_HELP (PATTERN_HELP_TYPES_RANGE_START + 15)

#define PATTERN_HELP_TYPES_RANGE_END (JELLY_FISH_HELP + 1)

#define NO_PATTERN_FOUND_HELP 350


#define HAS_LOGICAL_SOLUTION 361
#define NO_LOGICAL_SOLUTION 362

#define GRID_RATING 363
#define SOLVED_CELLS 364

#define APPLICATION_HELP 371
#define CONTACTS 380


#define HELP_TITLE 389
#define OPTIONS_GAME_TAB_HELP 390
#define OPTIONS_ASSISTANCE_TAB_HELP 391
#define OPTIONS_STATISTICS_TAB_HELP 392
#define OPTIONS_SETTINGS_TAB_HELP 393

#define EDIT_USER_TITLE 400
#define NEW_USER_TITLEG 401
#define ENTER_UNLOCK_KEY_TITLE 402
#define GAME_GRID_SOLVED_TITLE 403
#define SUCCESSFUL_REGISTRATION_TITLE 404


#define CHECK_FOR_CORRECT_GRID_TITLE 405
#define CORRECT_GRID_MESSAGE 406
#define NO_CORRECT_GRID_MESSAGE 407

#define NEW_VERSION_AVAILABLE_TITLE 408
#define NEW_VERSION_AVAILABLE_MESSAGE 409

#define VENDOR_WEBSITE_URL 1000
#define PURCHASE_AT 1001

